### ISSUE TITLE
Implement `to_numpy` method to speed up matplotlib with JAX arrays

### ISSUE THREAD

**Issue by patel-zeel** [jax-ml/jax#16054]
Hi,

As discussed in [this issue](https://github.com/matplotlib/matplotlib/issues/25882) and [corresponding PR](https://github.com/matplotlib/matplotlib/pull/25887) on `matplotlib`, JAX arrays can be significantly slow when used directly with `matplotlib`. This is because `matplotlib` has no easy way to convert JAX arrays to NumPy arrays before plotting and it expects other libraries to have `to_numpy()` method. I think `to_numpy()` implementation in JAX would be useful for the JAX users who might be using JAX arrays directly with `matplotlib` without knowing that it can be too slow. The following code reproduces the issue: 

```py
from time import time
import numpy as np

import jax
import jax.random as jr
import jax.numpy as jnp

import matplotlib.pyplot as plt

jax_array = jr.normal(jr.PRNGKey(0), (1000, 150))

def plot_hist(array):
    init = time()
    plt.figure()
    plt.hist(array)
    print(f"Time to plot: {time() - init:.2f} s")
    plt.show()

plot_hist(jax_array.ravel())  # takes around 5 seconds
plot_hist(np.array(jax_array.ravel()))  # takes around 0.05 seconds
```

- [x] Check for duplicate requests.
- [x] Describe your goal, and if possible provide a code snippet with a motivating example.

**Comment by oscargus** [comment]
The main reason Matplotlib doesn't use `__array__` is that there is no way to keep the unit support in Matplotlib working if `__array__` was used for conversion (as that will remove all the unit information and then there is no way to tell if there was unit information). 

There is a bit of a discussion in https://github.com/matplotlib/matplotlib/issues/22645 (and in the linked issues in the first post).

**Comment by hawkinsp** [comment]
I'm not entirely understanding the issue, based on a quick skim of the linked matplotlib discussion.

`__array__` is the standard protocol for converting an object to a NumPy array. Why do we need a second non-standard method? Under what circumstances and for what library would it ever do anything different to `__array__`?

**Comment by oscargus** [comment]
The reason for the request is that with `to_numpy`, plotting JAX arrays with Matplotlib will be significantly faster than it is today. This can easily be obtained by a user by first changing their JAX arrays to NumPy arrays, so will more be a way for JAX users to get faster plotting without having to know about the potential speed benefit of changing into NumPy arrays.

As for non-standard, at least  pandas, xarray, polars, and pyarrow support `to_numpy`. Although in several of those cases it may also make sense to have an explicit conversion to NumPy, so I am not arguing that you should add it, just want to put a bit more context in.

**Comment by hawkinsp** [comment]
Sure, but I do not understand why `matplotlib` cannot just call `__array__`, like everyone else...

**Comment by patel-zeel** [comment]
@hawkinsp my first emotion was exactly this, and I started my [PR](https://github.com/matplotlib/matplotlib/pull/25887) on `matplotlib` on this premise. I need to take a deeper look at the "unit information" concept but it seems `matplotlib` made certain design choices in very early stage which are restricting them to call `__array__` method on any object.

**Comment by hawkinsp** [comment]
@patel-zeel Why is the correct fix not for `matplotlib` to detect objects that support units and handle them by another path? I don't know the details, but that's what I'd try.

**Comment by patel-zeel** [comment]
@hawkinsp Maybe yes. I'll wait for `matplotlib` devs to see if there is a better "in-home" solution they can find.

**Comment by noahzhy** [comment]
This issue should be closed because that works fast in new version of matplotlib.

**Comment by jakevdp** [comment]
Thanks!
