### ISSUE TITLE
jax.scipy.stats refactoring tests

### ISSUE THREAD

**Issue by IlayMenahem** [jax-ml/jax#19354]
yesterday while working on scipy.stats I noticed two problems
- that there is a lot of code duplication in test\scipy_stats_tests, which can cause mistakes
- as far as i know method arguments for tests are only randomly generated, and there may be some edge cases that randomly generated tests won't cover

as for the first point, almost every test has the following structure
```python
@genNamedParametersNArgs(2)
  def testVonMisesPdf(self, shapes, dtypes):
    # create rng and establish information on the method
    rng = jtu.rand_default(self.rng())
    scipy_fun = osp_stats.vonmises.pdf
    lax_fun = lsp_stats.vonmises.pdf

     # create an args_maker
    def args_maker():
      x, kappa = map(rng, shapes, dtypes)
      kappa = np.where(kappa < 0, kappa * -1, kappa).astype(kappa.dtype)
      return [x, kappa]

    # check competability to lax and scipy.stats
    with jtu.strict_promotion_if_dtypes_match(dtypes):
      self._CheckAgainstNumpy(scipy_fun, lax_fun, args_maker, check_dtypes=False,
                            tol=1e-3)
      self._CompileAndCheck(lax_fun, args_maker)
```

And it could be replaced with
```python
def genericTest(self, shapes, dtypes, scipy_fun, lax_fun, args_maker_, check_dtypes=True,
          **kwargs):
  rng = jtu.rand_default(self.rng())

  def args_maker():
    return args_maker_(rng, shapes, dtypes)

  with jtu.strict_promotion_if_dtypes_match(dtypes):
    self._CheckAgainstNumpy(scipy_fun, lax_fun, args_maker, check_dtypes=check_dtypes,
                **kwargs)
    self._CompileAndCheck(lax_fun, args_maker)

…

def args_maker_VonMises(rng, shapes, dtypes):
  x, kappa = map(rng, shapes, dtypes)
  kappa = np.where(kappa < 0, kappa * -1, kappa).astype(kappa.dtype)
  return [x, kappa]

…

  @genNamedParametersNArgs(2)
  def testVonMisesPdf(self, shapes, dtypes):
    genericTest(self, shapes, dtypes, osp_stats.vonmises.pdf, lsp_stats.vonmises.pdf, 
                args_maker_VonMises, tol=1e-3)
```

**Comment by jakevdp** [comment]
Thanks for the suggestion. I think that's certainly possible (we use that sort of abstracted test harness elsewhere in the package), but a lot of those tests have slightly different specializations: different `args_maker`, different tolerances, different scipy version requirements, different modifications to the scipy function – I think you'd find that if you try to replace the whole test suite with the generic test, the generic test would become so complicated that in the end it may be clearer to just write it out directly.

For what it's worth, the generic pattern here is one in which we'v already abstracted-out most of the logic in test utilities – to my eye what is left is a pretty concise declaration of the special logic for each test.

What do you think?

**Comment by IlayMenahem** [comment]
yes, it does look like the improvement i'll be able to get will be more modest than i thought but i still there is room for improvement 

as for the specializations you mentioned 
- will needs addressing - different random number domains, different scipy version requirements, different modifications to the scipy function
- duplicates will be eliminated - different args_maker
- in **kwargs - different tolerances

i'll go deeper on the methods being used in the tests and see what can i do. 
i think it will be best if i'll make a PR draft with some of the tests using a the generic

**Comment by jakevdp** [comment]
I really don't think there's much to be gained here, to be honest.
