### ISSUE TITLE
patch release broke some dependencies

### ISSUE THREAD

**Issue by joamatab** [jax-ml/jax#19816]
### Description

latest patch release broke some integrations

https://github.com/gdsfactory/gplugins/issues/331

### System info (python version, jaxlib version, accelerator, etc.)

https://github.com/gdsfactory/gplugins/issues/331

**Comment by hawkinsp** [comment]
Hmm. While that has been deprecated for a while and issuing a warning I nthink, we probably shouldn't have removed it without communicating better how to update. Briefly: you need to use `jax.interpreter.mlir.register_lowering` instead.

This requires some mechanical changes: you need to build MLIR IR, instead of the older XLA HLO builder API.

**Comment by jakevdp** [comment]
Hi @joamatab – we're chatting about how to best resolve this. In the meantime, I'm curious to hear about your experience here: the relevant APIs here have been raising deprecation warnings for eight releases, starting with v0.4.16, and were finally removed in v0.4.24. Is there something else we could have done to better alert you and other downstream developers to these changes?

**Comment by joamatab** [comment]
Hi Jake,

I think what Peter was suggesting seems like a good idea,

What we are doing now is pinning the version of jaxlib so that  [sax](https://flaport.github.io/sax/), which is our circuit simulator that depends on [klujax](https://github.com/flaport/klujax) backend can install and run correctly

maybe because klujax is an optional backend for sax we did not see the warnings

Floris is the main author of sax and klujax, may have seen them

@flaport

**Comment by flaport** [comment]
That's weird... I haven't seen any deprecation warnings. Maybe I was doing something wrong? In particular, I was using the following line:

```python
xla.backend_specific_translations["cpu"][primitive] = ...
```

Which does not seem to yield any deprecation warnings for me

For now I wasn't able to figure out how to use `jax.interpreters.mlir.register_lowering`, but I figured out I can add my xla functions to  `_backend_specific_translations["cpu"]` directly for now. I do expect this will break in the future but in the meantime I can try to figure out how the new mechanism works. If anyone can give me some pointers I would be very happy 🙂

**Comment by jakevdp** [comment]
I see a deprecation warning in JAX 0.4.23:
```
>>> import jax
>>> print(jax.__version__)
0.4.23
>>> jax.interpreters.xla.backend_specific_translations
<stdin>:1: DeprecationWarning: jax.interpreters.xla.backend_specific_translations is deprecated. Register custom primitives via jax.interpreters.mlir instead.
  jax.interpreters.xla.backend_specific_translations
_BackendSpecificTranslationsAdapter(None, {})
```
But note that due to [the way Python Deprecation warnings work](https://docs.python.org/3/library/exceptions.html#DeprecationWarning), this will be suppressed if not triggered from `__main__`. In general I'd suggest configuring your CI to treat DeprecationWarnings as errors.

**Comment by flaport** [comment]
Thanks @jakevdp , Indeed, since my package is mostly used as a auxiliary library to which I hardly make any changes (and which I basically never execute as __main__), the DeprecationWarnings flew under the radar. I'll add a check to my CI to catch those warnings in the future.

**Comment by jan-david-fischbach** [comment]
> That's weird... I haven't seen any deprecation warnings. Maybe I was doing something wrong? In particular, I was using the following line:
> 
> ```python
> xla.backend_specific_translations["cpu"][primitive] = ...
> ```
> 
> Which does not seem to yield any deprecation warnings for me
> 
> For now I wasn't able to figure out how to use `jax.interpreters.mlir.register_lowering`, but I figured out I can add my xla functions to `_backend_specific_translations["cpu"]` directly for now. I do expect this will break in the future but in the meantime I can try to figure out how the new mechanism works. If anyone can give me some pointers I would be very happy 🙂

@flaport, `_backend_specific_translations` seems to have been finally removed in commit a9926f0f01a1e49118e7ebeb2ea19dfeb488222f
