### ISSUE TITLE
scan of device_put carry raises TypeError during the backward pass

### ISSUE THREAD

**Issue by fehiepsi** [jax-ml/jax#22045]
### Description

After jax 0.4.30, the following code raises
```
TypeError: body_fun output and input must have identical types, got
('ShapedArray(int32[], weak_type=True)', ['DIFFERENT ShapedArray(int32[], weak_type=True) vs. ShapedArray(float0[])', 'ShapedArray(float32[], weak_type=True)'], []).
```

```python
import jax

def f(ix, t):
    return ix, ix[1] + t

def scan_f(x):
    ix = jax.device_put((0, x))
    _, xs = jax.lax.scan(f, ix, jax.numpy.arange(10))
    return xs.sum()

jax.grad(scan_f)(1.)
```

This does not happen if we define
```
ix = 0, jax.device_put(x)
```
or
```
ix = jax.device_put(0), jax.device_put(x)
```

### System info (python version, jaxlib version, accelerator, etc.)

```
jax:    0.4.30
jaxlib: 0.4.30
numpy:  1.26.0
python: 3.10.13 (main, Aug 24 2023, 12:59:26) [Clang 15.0.0 (clang-1500.0.40.1)]
jax.devices (1 total, 1 local): [CpuDevice(id=0)]
process_count: 1
```

**Comment by yashk2810** [comment]
I'll take a look. Thanks for the minimal repro!

**Comment by yashk2810** [comment]
I think this is a case of inconsistent dtypes.. the following works where everything is a float (instead of a combination of float and int).

```
In [4]: import jax
   ...:
   ...: def f(ix, t):
   ...:     return ix, ix[1] + t
   ...:
   ...: def scan_f(x):
   ...:     ix = jax.device_put((0., x))
   ...:     _, xs = jax.lax.scan(f, ix, jax.numpy.arange(10, dtype=np.float32))
   ...:     return xs.sum()
   ...:
   ...: jax.grad(scan_f)(1.)
Out[4]: Array(10., dtype=float32, weak_type=True)
```

The error message still sucks though. I'll look into improving it.

**Comment by nireekshak** [comment]
Hi @fehiepsi, 
Thanks for reporting this, could you try to execute the code in 0.4.34 and higher Jax version, it seems to be working fine.  Attaching [gist ](https://colab.sandbox.google.com/gist/nireekshak/05fe6c53366ee8fba6e3e94411cb9a52/-22045.ipynb)for your reference.
Thank you.

**Comment by fehiepsi** [comment]
Let's close this issue then. Thanks!
