### ISSUE TITLE
Missing jax-cuda12-plugin 0.4.33 arm wheel

### ISSUE THREAD

**Issue by luyug** [jax-ml/jax#23824]
### Description

The latest release (0.4.33) of `jax-cuda12-plugin` on pypi is missing arm build wheel. As a result, the latest version of jax cannot be installed.

### System info (python version, jaxlib version, accelerator, etc.)

GH200

**Comment by hawkinsp** [comment]
Should be fixed. Try now.

(I'm not sure why it failed to upload, but I just manually uploaded it.)
