### ISSUE TITLE
Bug- False "UserWarning: Explicitly requested dtype <class 'jax.numpy.int64'> requested in astype is not available, and will be truncated to dtype int32 

### ISSUE THREAD

**Issue by eadadi** [jax-ml/jax#23829]
### Description

```python
Python 3.9.19 (main, May  6 2024, 19:43:03)
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import jax
>>> import tensorflow_probability.substrates.jax as tfp
>>> tfd = tfp.distributions
>>> rng = jax.random.PRNGKey(0)
>>> tfd.OneHotCategorical(logits=jax.random.normal(key=rng,shape=(3,4)), dtype=jax.numpy.float32).sample(seed=rng)
/home/user/anaconda3/envs/ml_exp/lib/python3.9/site-packages/jax/_src/numpy/array_methods.py:68: UserWarning: Explicitly requested dtype <class 'jax.numpy.int64'> requested in astype is not available, and will be truncated to dtype int32. To enable more dtypes, set the jax_enable_x64 configuration option or the JAX_ENABLE_X64 shell environment variable. See https://github.com/google/jax#current-gotchas for more.
  return lax_numpy.astype(arr, dtype, copy=copy, device=device)
Array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.]], dtype=float32)
```

I explicitly set `jnp.float32` and did not ask for `int` anywhere, but received the warning

### System info (python version, jaxlib version, accelerator, etc.)

jax:    0.4.30
jaxlib: 0.4.30
numpy:  1.26.4
python: 3.9.19 (main, May  6 2024, 19:43:03)  [GCC 11.2.0]
jax.devices (1 total, 1 local): [CpuDevice(id=0)]
process_count: 1
platform: uname_result(system='Linux', node='user', release='6.8.0-45-generic', version='#45-Ubuntu SMP PREEMPT_DYNAMIC Fri Aug 30 12:02:04 UTC 2024', machine='x86_64')

**Comment by jakevdp** [comment]
Thanks for the report! This warning is arising becuase `tensorflow_probability` passes an `int64` to JAX. You can see this by re-executing your code after running the following:
```python
import warnings
warnings.simplefilter('error')
```
This will turn the warning into an error with a full traceback, which points to the place where this problematic dtype is passed, which is here: https://github.com/tensorflow/probability/blob/c6c86e788516a9b16958460528867735a721ef40/tensorflow_probability/python/internal/backend/numpy/random_generators.py#L106

If this warning is a problem to you, you could think about reporting it to the `tensorflow_probability` maintainers, but there's nothing JAX can do to fix this short of removing the warning entirely.
