### ISSUE TITLE
Add .at[].subtract

### ISSUE THREAD

**Issue by carlosgmartin** [jax-ml/jax#23933]
**Feature request:** Add a `subtract` method to [jax.numpy.ndarray.at](https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.ndarray.at.html).

**Comment by superbobry** [comment]
This sounds reasonable, even though you can do `.add(-x)` for signed types.

@jakevdp wdyt?

**Comment by jakevdp** [comment]
I think this is reasonable. We could do it the easy way, with something like this:
```
def subtract(self, x):
  return self.add(-x)
```
but as @superbobry points out, this would fail for unsigned types.

The full solution is a bit more work: it would involve defining a `lax.scatter_subtract` primitive with appropriate autodiff rules, and dispatching to that.
