### ISSUE TITLE
More human readable doc/variable name for function like jnp.where().

### ISSUE THREAD

**Issue by nanoric** [jax-ml/jax#24245]
Please:
Rename ```x``` and ```y``` into ```values_for_true``` and ```values_for_false``` or ```other clear words```. So people don't need to check document to know jnp.where()'s behaviour: Whether result is get from ```x``` or ```y``` when ```condition``` is true.

For a people who usually use jax.numpy, this might not be a problem. But for every one who ever used other liberary, especially pandas, and not only focus on develop with only jax, checking docs carefully is required before using a any function like x.where(). Because even these function has idendical names, they might behaves totally different. Checking every function's behaviour before using it is necessary. But checking docs for every funciton's behaviour is costy.

> Especially when I check jax.numpy's docs, information I reqruied didn't appeares at the first line, not the second and third line or the last line, not in the description of function, not in the description of parameters. It is in the description of return values. So unexpected.

I recommand rename ```x``` and ```y``` into ```values_for_true``` and ```values_for_false``` or ```other clear words```, so people will understant function's exact behaviour without checking docs: Most IDE will popup a arguments list when typing ```.where(```.

**Comment by lockwo** [comment]
This comes from numpy, which jax matches (usually) the docstrings/naming of: https://numpy.org/doc/2.0/reference/generated/numpy.where.html

**Comment by jakevdp** [comment]
Thanks for the request! Indeed the argument names in `jnp.where` are constructed to match those in `np.where`, and while I agree it would be clearer if the variable names were more informative, that would be an API breakage at this point, as existing code likely uses things like `jnp.where(condition, x=x, y=y)`.

If you have suggestions for how we could make the documentation clearer without making breaking API changes, we'd be happy to hear them. Thanks!
