### ISSUE TITLE
[Apple GPU (Metal) plugin] (Stable) HLO support ?

### ISSUE THREAD

**Issue by janpfeifer** [jax-ml/jax#24365]
hi,

I maintain [GoMLX](github.com/gomlx/gomlx) a machine learning framework based on XLA, and when trying to use it on Apple Metal (GPU) I bumped on the error bellow.

`PJRT error (code=3): METAL only supports MLIR format input.`

Are there any plans to support HLO ? GoMLX is feeding it with the output of the XlaBuilder, the compiled `HloModuleProto` proto that it exports.

Any other suggestions ?

many thanks!

Full log:

(Notice a couple of the lines are GoMLX specific, I named the plugin "cpu", but it's the one downloaded from `jax-metal` pip package)

```
Loaded PJRT "cpu" plugin (/usr/local/lib/gomlx/pjrt/pjrt_c_api_cpu_plugin.dylib) v0.47
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
W0000 00:00:1729171386.464515  169742 mps_client.cc:510] WARNING: JAX Apple GPU support is experimental and not all JAX functionality is correctly supported!
Metal device set to: Apple M2 Pro
I0000 00:00:1729171386.480718  169742 service.cc:145] XLA service 0x6000024bc400 initialized for platform METAL (this does not guarantee that XLA will be used). Devices:
I0000 00:00:1729171386.480743  169742 service.cc:153]   StreamExecutor device (0): Metal, <undefined>
I0000 00:00:1729171386.482386  169742 mps_client.cc:406] Using Simple allocator.
I0000 00:00:1729171386.482398  169742 mps_client.cc:384] XLA backend will use up to 11452858368 bytes on device 0 for SimpleAllocator.
        client: Client[plugin="cpu", platform="METAL - metal_0.5.1", single-process]
--- FAIL: TestEndToEnd (1.45s)
    gopjrt_test.go:44: 
                Error Trace:    /Users/m1/Projects/gopjrt/gopjrt_test.go:44
                Error:          Received unexpected error:
                                PJRT error (code=3): METAL only supports MLIR format input.
```

**Comment by justinjfu** [comment]
@shuhand0

**Comment by janpfeifer** [comment]
To answer my own question, I think by MLIR the PJRT model means StableHLO, encoded as "mlir" -- but not having used StableHLO I was not aware of the nuance.

And I was pointed to the code in PyTorch XLA that deals with the same situation, if the PJRT doesn't accept "hlo" by converting it to StableHLO (as an `mlir::ModuleOp` object).

Here is the link for others bumping into the same issue:

https://github.com/pytorch/xla/blob/1bd17f7be2de80d82cba89f00732874d697871c9/torch_xla/csrc/runtime/pjrt_computation_client.cc#L619

Closing the issue.

**Comment by shuhand0** [comment]
JAX-Metal plugin accepts Stablehlo (MLIR) as input from JAX and compiles to an internal MLIR dialect. HLO computation as an IR used by XLA is not supported by JAX-Metal.
