### ISSUE TITLE
TeLU activation addition

### ISSUE THREAD

**Issue by cvnad1** [jax-ml/jax#24396]
Please:

- [x] Check for duplicate requests.
- [x] Describe your goal, and if possible provide a code snippet with a motivating example.

I want to add a TeLU activation function. Please have a look at the following research articles.

https://arxiv.org/abs/2402.02790

https://ieeexplore.ieee.org/document/9301084

**Comment by lockwo** [comment]
There's a lot of activation functions (at least 400 https://arxiv.org/abs/2402.09092). It seems hard to justify including a very recent one that also doesn't have any citations.

**Comment by cvnad1** [comment]
Thanks for the quick and prompt response. I have read through the paper and although there are not many citations, the results were good. I was planning to experiment with different activation functions myself with JAX regarding their performance and thought it would make a good addition.

Anyway, thanks again !!!
