### ISSUE TITLE
Expose XLA option exec_time_optimization_effort through jax

### ISSUE THREAD

**Issue by shukladivyansh** [jax-ml/jax#24625]
There's an ExecutionOption in XLA called [exec_time_optimization_effort](https://github.com/openxla/xla/blob/7c4ca04fec74f59a3426294300c4c77fdcbc05a4/xla/xla.proto#L1154) which allows to tradeoff compiled binary performance for compilation time.

It would be great if this option could be made available through jax. Maybe something like this.

```python
def f(x):
      return jnp.sqrt(x ** 2) + 1.

f_jit = jit(f)
lowered = f_jit.lower(1.)
lowered.compile( 
    compiler_options={
        "xla_exec_time_optimization_effort": -0.7,
    }
)
```

**Comment by mattjj** [comment]
Thanks for the request! I think this should be handled by #24673
