### ISSUE TITLE
Issue: conda install Command Fails in zsh Due to Wildcard Expansion

### ISSUE THREAD

**Issue by Li-Jesse-Jiaze** [jax-ml/jax#24661]
### Description

When running the following command directly in `zsh`:

```zsh
conda install jaxlib=*=*cuda* jax cuda-nvcc -c conda-forge -c nvidia
```

The following error is raised:
```
zsh: no matches found: jaxlib=*=*cuda*
```

#### Cause
In `zsh`, the `*` character is interpreted as a wildcard, leading to an attempt to expand filenames or paths that match the pattern `jaxlib=*=*cuda*`. Since no matching files or paths are found, `zsh` throws an error.

#### Suggested Solution
A simple fix is to enclose the pattern in double quotes to prevent wildcard expansion. The following command works in both `bash` and `zsh`:

```zsh
conda install "jaxlib=*=*cuda*" jax cuda-nvcc -c conda-forge -c nvidia
```
--- 

This should clearly outline the issue and provide a helpful suggestion for the JAX team.

### System info (python version, jaxlib version, accelerator, etc.)

jax:    0.4.13
jaxlib: 0.4.12
numpy:  1.23.5
python: 3.8.20 (default, Oct  3 2024, 15:24:27)  [GCC 11.2.0]
jax.devices (1 total, 1 local): [gpu(id=0)]
process_count: 1

$ nvidia-smi
Fri Nov  1 14:34:19 2024
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.76.01              Driver Version: 552.22         CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4060 ...    On  |   00000000:01:00.0 Off |                  N/A |
| N/A   49C    P8              1W /   83W |    1068MiB /   8188MiB |      4%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A     22685      C   /python3.8                                  N/A      |
+-----------------------------------------------------------------------------------------+

**Comment by dfm** [comment]
Thanks! We (the JAX team) don't formally support the conda installation flow, but we're always happy to accept contributions to the docs. Would you be willing to submit this change as a pull requests?
