### ISSUE TITLE
Wrong description in the document of Cholesky factorization

### ISSUE THREAD

**Issue by jiaxi98** [jax-ml/jax#24691]
### Description

In the [document](https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.linalg.cholesky.html) of the function jax.numpy.linalg.cholesky, the description of the parameter **upper** is inconsistent:

* upper ([bool](https://docs.python.org/3/library/functions.html#bool)) – if True, compute the upper Cholesky decomposition L. if False (default), compute the lower Cholesky decomposition U.

While in the formula above, U denotes upper Cholesky while L denotes lower. Please update the document.

### System info (python version, jaxlib version, accelerator, etc.)

Document issue.

**Comment by jakevdp** [comment]
Thanks for catching this! Would you like to send a PR with the fix? If not I can take care of it.

**Comment by jiaxi98** [comment]
Okay, I will create a PR for this.

**Comment by jiaxi98** [comment]
I have created a PR: https://github.com/jax-ml/jax/pull/24692. BTW, only the cholesky function in numpy package has the issue while scipy package cholesky is correct. But they are not consistent, numpy uses lower factorization as default while scipy uses upper as default

**Comment by jakevdp** [comment]
Fixed by #24692
