### ISSUE TITLE
time.sleep affects the execution time of JAX

### ISSUE THREAD

**Issue by horse6** [jax-ml/jax#24941]
### Description

I have a function that takes significantly longer to execute when running on Ray compared to running it directly. Then I took the function from the Ray worker and ran it directly, and I found that the execution time was affected by the time.sleep duration. This function represents one step of network training, and it has already been compiled into an executable file that can be directly loaded. The input data has also been saved. The reproducible code is as follows:
Note: 
The executable file was compiled in an NVIDIA A100 80G environment, and only **one** GPU is used.
All files are [here](https://drive.google.com/file/d/1RdjReWclIKI_t2RBjhXXURxTs9Z2Lqq6/view?usp=sharing).

```python
import os
os.environ["XLA_PYTHON_CLIENT_ALLOCATOR"] = "platform"

import jax
jax.config.update("jax_platform_name", "gpu")
from jax.lib import xla_bridge as xb
import pickle
backend = xb.get_backend("cuda")

with open("loaded_exe", "rb") as f:
    a = f.read()
    compiled = backend.deserialize_executable(a)

input_arr = []
for i in range(10):
    with open("arrays.pkl", "rb") as f:
        input_array0 = pickle.load(f)
        input_arr.append(input_array0)

import time
total_time = 0.0
for i in range(1, 3000):
    # The following line will affect the execution time of execute_sharded_on_local_devices.
    # Different time.sleep arg(eg. 0.3,0.8) has different effect.
    # time.sleep(0.8)
    _t = time.time()
    out_ = compiled.execute_sharded_on_local_devices(input_arr[i%10])
    out_[0][0].block_until_ready()
    tmp = time.time() - _t
    total_time += tmp
    print(f"{i=}: avg time: {total_time/i}, cur time: {tmp}")
print(out_[0])
```

### System info (python version, jaxlib version, accelerator, etc.)

![captrue](https://github.com/user-attachments/assets/2e506f6e-2a4a-49ab-8438-e2957562aee1)

**Comment by superbobry** [comment]
This looks WAI to me. You would want the `time.sleep()` call before

```
out_ = compiled.execute_sharded_on_local_devices(input_arr[i%10])
```

and

```
out_[0][0].block_until_ready()
```

in order for the sleeping to be done in parallel with compute.

**Comment by horse6** [comment]
In fact, I am simulating a scenario where there are some other computations before calling this function. There will be a time interval between the two calls to `execute_sharded_on_local_devices`. I think this time interval should not affect the execution time of `execute_sharded_on_local_devices`, but in this example, it seems to have an impact. I am not sure why this is happening.

**Comment by superbobry** [comment]
I think you aren't getting the overlap you expect because your code does `.block_until_ready()`. You probably want

```
out_ = compiled.execute_sharded_on_local_devices(input_arr[i%10])
do_some_other_compute()
jax.block_until_ready(out_)
```

Does this help?

**Comment by horse6** [comment]
Thank you for your response, but what confuses me is that the execution time of this function is affected by a sleep unrelated to it (I think that `sleep` and `execute_sharded_on_local_devices` should be independent; please point out if this is incorrect). Below are the results for three cases: no `sleep`, `sleep` for 0.3 seconds, and `sleep` for 0.8 seconds. You can see that the average execution time is affected (though single-run times fluctuate).
### no sleep:
![nosleep](https://github.com/user-attachments/assets/9d165073-7181-4fad-9fa4-6bc33e1b46ce)

### sleep for 0.3s:
![sleep0 3](https://github.com/user-attachments/assets/64cae5a0-9397-4663-8821-0c9a7999dda4)

### sleep for 0.8s:
![sleep0 8](https://github.com/user-attachments/assets/394036d0-0aed-4f3d-b196-a74aab4ead1a)

**Comment by jakevdp** [comment]
What if you do `jax.block_until_ready(out_)` rather than `out_[0][0].block_until_ready()`?

Also, I'd suggest using Python's [`timeit` module](https://docs.python.org/3/library/timeit.html) (or for convenience, IPython's [`%timeit` magic](https://ipython.readthedocs.io/en/stable/interactive/magics.html#magic-timeit) which wraps `timeit`) to work around potential pitfalls of `time.time` for benchmarks.

**Comment by horse6** [comment]
Using `jax.block_until_ready(out_)` and measuring the execution time with `timeit` has results similar results as before.

### no sleep:
![timeitnosleep](https://github.com/user-attachments/assets/bb5ed06e-acfb-4cfc-a7b9-9ee3cf5dd9d5)

### sleep for 0.8s (total execution time includes 80 seconds for `sleep`): 
![timeitsleep](https://github.com/user-attachments/assets/4a37a6dd-0154-4800-ad34-779986b502cf)

**Comment by jakevdp** [comment]
Thanks for checking on that. I suspect what's going on is that there is asynchronous buffer deletion happening in the background that is occurring during the sleep when present, and affecting the benchmark otherwise.

**Comment by horse6** [comment]
Thank you for your reply. After enabling pre-allocation of GPU memory in the code, this issue was resolved.
