### ISSUE TITLE
Slow import time: can it be reduced?

### ISSUE THREAD

**Issue by jeertmans** [jax-ml/jax#24967]
### Description

Hello!

As part of optimizing my library, I noticed that importing `jax.numpy` takes quite some time, especially with respect to NumPy:

```bash
> hyperfine "python -c 'import jax.numpy as jnp'" "python -c 'import numpy as np'"
Benchmark 1: python -c 'import jax.numpy as jnp'
  Time (mean ± σ):     343.6 ms ±  50.8 ms    [User: 901.4 ms, System: 36.2 ms]
  Range (min … max):   284.8 ms … 430.7 ms    10 runs
 
Benchmark 2: python -c 'import numpy as np'
  Time (mean ± σ):      72.8 ms ±  11.7 ms    [User: 433.9 ms, System: 10.6 ms]
  Range (min … max):    66.5 ms … 109.7 ms    42 runs
 
Summary
  python -c 'import numpy as np' ran
    4.72 ± 1.03 times faster than python -c 'import jax.numpy as jnp'
```

I know that JAX does a lot of things that NumPy doesn't, especially handling the potential presence of TPU/GPU/etc., which probably explains why it is slower.

Still, by looking at the import time of each module, with:

```bash
python -X importtime -c 'import jax.numpy as jnp' 2> import.log
tuna import.log
```

I noticed that almost half of the import time is dedicated to import modules that are very likely not going to be used my most users (as people rarely have a TPU in their development machine), and was wondering if some of those imports could be lazily performed?

![image](https://github.com/user-attachments/assets/1d677ad7-6e74-4efd-a474-7dac1e8180a9)

I mean, 300 ms isn't a big issue and usually people are not eve noticing it, but import time quickly add up in larger libraries :-) I understand it might not be that easy, especially as some code might need to run before any array operation is performed, but I preferred to post an issue about this.

Thanks for your great package!

### System info (python version, jaxlib version, accelerator, etc.)

```
jax:    0.4.35
jaxlib: 0.4.34
numpy:  2.1.3
python: 3.11.8 (main, Feb 25 2024, 04:18:18) [Clang 17.0.6 ]
device info: NVIDIA T500-1, 1 local devices"
process_count: 1
platform: uname_result(system='Linux', node='jeertmans', release='6.8.0-48-generic', version='#48-Ubuntu SMP PREEMPT_DYNAMIC Fri Sep 27 14:04:52 UTC 2024', machine='x86_64')
```

**Comment by hawkinsp** [comment]
A quick note: I suspect you're misattributing some of the time here. Yes, it looks like `cloud_tpu_init` is taking the time. But if you drill down, you'll see that comes because it happens to be the first to transitively import `ml_dtypes`, and that in turn comes almost entirely because `ml_dtypes` imports NumPy. If we didn't import `cloud_tpu_init`, the time would just be charged somewhere else because we're unconditionally going to import both of those modules.

In general 300ms isn't terrible, but PRs are welcome.

**Comment by jeertmans** [comment]
Indeed, I was too quick, as in turns out `ml_dtypes`'s import time is almost entirely taken by NumPy itself. It leaves much less room for improvement then ^^'.

My request is no longer relevant I guess, apologies for the inconvenience!
