### ISSUE TITLE
libtpu.so Not Found for JAX TPU 0.4.14

### ISSUE THREAD

**Issue by LeoXinhaoLee** [jax-ml/jax#24987]
### Description

Hi, I'm trying to **install jax[tpu]==0.4.14 on a V5e-256 TPU pod** by `pip install -U "jax[tpu]==0.4.14" -f https://storage.googleapis.com/jax-releases/libtpu_releases.html`. 

However, after installation, when I launch a jax job, I got the below error:

```
RuntimeError: Unable to initialize backend 'tpu': INTERNAL: Failed to open /home/XXXXX/.local/lib/python3.10/site-packages/libtpu/libtpu.so: /home/XXXXX/.local/lib/python3.10/site-packages/libtpu/libtpu.so: cannot open shared object file: No such file or directory (set JAX_PLATFORMS='' to automatically choose an available backend)
```

I then check ed`/home/XXXXX/.local/lib/python3.10/site-packages/libtpu` and found no `libtpu.so` is there. Could you please help me with this? Thank you very much! 

### System info (python version, jaxlib version, accelerator, etc.)

```
flax                     0.7.0
jax                      0.4.14
jaxlib                   0.4.14
optax                    0.1.7
orbax-checkpoint         0.5.16
```

**Comment by jakevdp** [comment]
I can reproduce this with `jax[tpu]==0.4.14`, which pins `libtpu-nightly==0.1.dev20230727`. If I update to `jax[tpu]==0.4.16`, which pins `libtpu-nightly==0.1.dev20230918`, the issue goes away.

I suspect this means that that version of libtpu-nightly has a bug that was undetected at the time; your best bet is probably to upgrade to a more recent JAX release.

**Comment by LeoXinhaoLee** [comment]
I see. Will try to upgrade my JAX. Thank you very much!
