### ISSUE TITLE
About FFI failure: Failed to destroy GPU Graph

### ISSUE THREAD

**Issue by victoryang00** [jax-ml/jax#25141]
### Description

I'm using the latest Nvidia driver 560 and try to work using libcuda_e2e in the jax_ffi_example folder.
```
E1127 02:49:41.806995 1032605 gpu_command_buffer.cc:140] Failed to destroy GPU graph: CUDA error: Failed to destroy CUDA graph: CUDA_ERROR_INVALID_VALUE: invalid argument
E1127 02:49:41.807043 1032605 pjrt_stream_executor_client.cc:3085] Execution of replica 0 failed: INTERNAL: CUDA error: Failed to end stream capture: CUDA_ERR OR_STREAM_CAPTURE_INVALIDATED: operation failed due to a previous error during capture
```
It worked on my other machine with Nvidia driver 535. I guess this is related to the driver version? How can I resolve this?

### System info (python version, jaxlib version, accelerator, etc.)
<img width="597" alt="Snipaste_2024-11-27_12-57-46" src="https://github.com/user-attachments/assets/4971d803-54c8-480a-af74-9d0e8133af68">

jax version 0.4.35

**Comment by dfm** [comment]
Pinging @ezhulenev in case he has advice. (Of note: [that example](https://github.com/jax-ml/jax/blob/aff7714dc0f49cc0097e4db08e028b68182c8ab9/examples/ffi/src/jax_ffi_example/cuda_examples.cu) uses the command buffer.)

**Comment by ezhulenev** [comment]
Do you see any other errors in the logs? I think we need @nouiz here. The error looks like you tried to capture something that is not supported (i.e. device to host memory copy or stream synchronization), but I wonder why it works with older driver.

Can you try to run with env variable `TF_CPP_VMODULE=gpu_command_buffer=100,command_buffer_cmd=100,command_buffer_thunk=100`

**Comment by nouiz** [comment]
Which version of JAX do you use?
Do you use external extension?

**Comment by victoryang00** [comment]
The latest Jax commit and I'm using the external ffi with cuda extension.
