### ISSUE TITLE
Allow using jax.jit as decorator with arguments

### ISSUE THREAD

**Issue by cool-RR** [jax-ml/jax#25194]
- [X] Check for duplicate requests. 
- [X] Describe your goal, and if possible provide a code snippet with a motivating example.

I'm sorry if this was requested before, I couldn't find an existing issue but I imagine I'm not the first person who thought of this. 

It would be nice if instead of this: 

```python
@functools.partial(jax.jit, static_argnames=('x', 'y'))
def foo(x, y):
    ...
```

We could have this:

```python
@jax.jit(static_argnames=('x', 'y'))
def foo(x, y):
    ...
```

What do you think?

**Comment by jakevdp** [comment]
Hi - thanks for bringing this up! We've discussed this previously in #10061 and #22061, and at the time decided that the additional complexity of the decorator factory pattern is not warranted.

**Comment by jakevdp** [comment]
I think I'll close this in favor of #10061, which is the canonical issue on this topic. Thanks!

**Comment by cool-RR** [comment]
Ah, too bad. I hope you'll change your minds in the future. Thanks for the links.
