### ISSUE TITLE
Slowdown of jax::lax::while_loop on CPU between 0.4.31 and 0.4.33

### ISSUE THREAD

**Issue by bondquant** [jax-ml/jax#25190]
### Description

Hi Sirs,

Something was released between versions 0.4.31 and 0.4.33 that is causing a big slowdown in `jax::lax::while_loop` on CPUs. I could distill the problem to the following code, which runs in 2 seconds on 0.4.31, but in 42 seconds on 0.4.33 (and later versions). Not sure related or not, but people have mentioned increased recompilation times of weak types in [another issue](https://github.com/jax-ml/jax/issues/23690) (but it was closed, so may not be related).

Here is my code. I could run it in Colab and it's reproducible. You just change the Jax version in the header to 0.4.33 to observe the slowdown.

```
%pip install jax[cuda12]==0.4.31
import os
num_cpu = 96
os.environ['XLA_FLAGS'] = f'--xla_force_host_platform_device_count={num_cpu}'
import jax
from jax import numpy as jnp, lax
import timeit
start = timeit.default_timer()

steps = 2 ** 22
foo = jnp.arange(steps)
stop = jnp.max(foo)
cpu_devices = jax.devices('cpu')
cpu_count = jax.local_device_count('cpu')
cpu_range = jnp.arange(cpu_count)

def _episode(_):
    return lax.while_loop(lambda u: u[0] < stop
                          , lambda u: (jnp.maximum(u[0], foo[u[1]]), u[1] + 1)
                          , (0, 0))[1]

bar = jax.pmap(_episode, devices=cpu_devices)(cpu_range)
bar.block_until_ready()

finish = timeit.default_timer()
print(f'Elapsed time {finish - start:.2f}s')
```

Prints `Elapsed time 2.21s` on Jax 0.4.31, but `Elapsed time 42.08s` on Jax 0.4.33.

### System info (python version, jaxlib version, accelerator, etc.)

Run in Colab, with 96 host devices

```
jax:    0.4.31
jaxlib: 0.4.31
numpy:  1.26.4
python: 3.10.12 (main, Nov  6 2024, 20:22:13) [GCC 11.4.0]
jax.devices (96 total, 96 local): [CpuDevice(id=0) CpuDevice(id=1) ... CpuDevice(id=94) CpuDevice(id=95)]
process_count: 1
platform: uname_result(system='Linux', node='083577bc3e73', release='6.1.85+', version='#1 SMP PREEMPT_DYNAMIC Thu Jun 27 21:05:47 UTC 2024', machine='x86_64')
```

And 

```
jax:    0.4.33
jaxlib: 0.4.33
numpy:  1.26.4
python: 3.10.12 (main, Nov  6 2024, 20:22:13) [GCC 11.4.0]
jax.devices (96 total, 96 local): [CpuDevice(id=0) CpuDevice(id=1) ... CpuDevice(id=94) CpuDevice(id=95)]
process_count: 1
platform: uname_result(system='Linux', node='083577bc3e73', release='6.1.85+', version='#1 SMP PREEMPT_DYNAMIC Thu Jun 27 21:05:47 UTC 2024', machine='x86_64')
```

**Comment by bondquant** [comment]
Could be related to this also: [https://github.com/jax-ml/jax/issues/23302](https://github.com/jax-ml/jax/issues/23302)

**Comment by bondquant** [comment]
The slowdown impacts `lax::scan` too (although to a less extent). Just replace the function above with this:

```
def _episode(_):
  return lax.scan(lambda c, x: (jnp.maximum(c, x), c+1)
                  , 0
                  , foo)[0]
```

`Elapsed time 1.96s` on 0.4.31 vs `Elapsed time 33.49s` on 0.4.33

**Comment by tilmantroester** [comment]
I've seen the same effect (x10 speed-up going from 0.4.34 back to 0.4.31) for code using `jax.lax.while_loop` in `jax.lax.map` on a single CPU.

**Comment by hawkinsp** [comment]
@ezhulenev @penpornk

**Comment by hawkinsp** [comment]
You can disable the thunks runtime `XLA_FLAGS=--xla_cpu_use_thunk_runtime=false` to get the old behavior under the newer JAX.

**Comment by tilmantroester** [comment]
Are there downsides to disabling the thunks runtime?

**Comment by hawkinsp** [comment]
> Are there downsides to disabling the thunks runtime?

No immediate ones. At some point we want to delete the older runtime, so ideally we'd fix any performance regressions by then!

**Comment by carlosgmartin** [comment]
@hawkinsp Does JAX have some sort of test suite that automatically detects performance regressions like this one? If not, it might be a good idea to create one.
