### ISSUE TITLE
"IndexError: list index out of range" raised by _check_carry_type in lax/control_flow/loops.py

### ISSUE THREAD

**Issue by carlosgmartin** [jax-ml/jax#25332]
### Description

```python3
import chex
import jax

@chex.dataclass(frozen=True)
class Class:
    field: int

def f(x, _):
    return x, None

jax.lax.scan(f, Class(field=3), length=10)
```
```
$ python3 -m pip install -U jax==0.4.35
$ python3 test.py
$ python3 -m pip install -U jax==0.4.36
$ python3 test.py
Traceback (most recent call last):
  File "/Users/carlos/test.py", line 14, in <module>
    jax.lax.scan(f, Class(field=3), length=10)
  File "/Users/carlos/venv/lib/python3.12/site-packages/jax/_src/traceback_util.py", line 180, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/carlos/venv/lib/python3.12/site-packages/jax/_src/lax/control_flow/loops.py", line 303, in scan
    _check_carry_type('scan body', f, init, out_tree_children[0], carry_avals_out)
  File "/Users/carlos/venv/lib/python3.12/site-packages/jax/_src/lax/control_flow/loops.py", line 383, in _check_carry_type
    + f'  * {diffs[-1]}.\n')
             ~~~~~^^^^
IndexError: list index out of range
```
As shown above, this issue was introduced between [0.4.35](https://github.com/jax-ml/jax/releases/tag/jax-v0.4.35) and [0.4.36](https://github.com/jax-ml/jax/releases/tag/jax-v0.4.36).

It is caused by [this line of code](https://github.com/jax-ml/jax/blob/ad00ee1e06eb8063b8ed081ef410dbf75fd246a3/jax/_src/lax/control_flow/loops.py#L365) triggering [this line of code](https://github.com/jax-ml/jax/blob/ad00ee1e06eb8063b8ed081ef410dbf75fd246a3/jax/_src/lax/control_flow/loops.py#L383). If I insert the following lines right before it:
```python3
print(in_carry_tree)
print(out_carry_tree)
print(diffs)
exit()
```
this is the output:
```
PyTreeDef(CustomNode(Class[[GetAttrKey(name='field')]], [*]))
PyTreeDef(CustomNode(Class[('field',)], [*]))
[]
```
There are two mismatches: `[]` vs. `()`, and the presence or absence of [`GetAttrKey`](https://github.com/jax-ml/jax/blob/ad00ee1e06eb8063b8ed081ef410dbf75fd246a3/jax/_src/tree_util.py#L733).

A class without fields also triggers this error.

### System info (python version, jaxlib version, accelerator, etc.)

```
jax:    0.4.36
jaxlib: 0.4.36
numpy:  1.26.4
python: 3.12.7 (main, Oct  1 2024, 02:05:46) [Clang 15.0.0 (clang-1500.3.9.4)]
device info: cpu-1, 1 local devices"
process_count: 1
platform: uname_result(system='Darwin', node='Carloss-MacBook-Pro-2.local', release='23.6.0', version='Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:46 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6031', machine='arm64')
```

**Comment by superbobry** [comment]
I did a bisect and it looks like this is caused by #24906. @IvyZX can you have a look please?

**Comment by jsspencer** [comment]
The issue is in chex, and is fixed at HEAD. Upgrading chex to the latest commit works for me:

```
pip install -U --force --no-deps 'git+https://github.com/google-deepmind/chex@f0b6b503a5fb625a380a6b318ec1f6d2abd9b9bf'
```

We just need a new release of chex, I think.

**Comment by IvyZX** [comment]
https://github.com/jax-ml/jax/pull/25355 should also fix this on JAX python level. A new JAX release might come out today that includes this.
