### ISSUE TITLE
vmap support for optimization barrier

### ISSUE THREAD

**Issue by MattWiethoff** [jax-ml/jax#25365]
Calling jax.lax.optimization_barrier inside of a vmap'd function yields: `NotImplementedError: Batching rule for 'optimization_barrier' not implemented`

This would be super-useful if supported, thanks!

**Comment by yashk2810** [comment]
Fixed by https://github.com/jax-ml/jax/commit/944d822ce64450f698bd9b4e8236421ade401e84
