### ISSUE TITLE
jax.nn.one_hot should not allow float inputs

### ISSUE THREAD

**Issue by danijar** [jax-ml/jax#25484]
### Description

Currently, jax.nn.one_hot() fails silently on float inputs:

```
>>> jax.nn.one_hot(jnp.array(0.0, jnp.float32), 4)
Array([1., 0., 0., 0.], dtype=float32)

>>> jax.nn.one_hot(jnp.array(0.5, jnp.float32), 4)
Array([0., 0., 0., 0.], dtype=float32)

>>> jax.nn.one_hot(jnp.array(1.9999999, jnp.float32), 4)
Array([0., 0., 0., 0.], dtype=float32)

>>> jax.nn.one_hot(jnp.array(1.99999999, jnp.float32), 4)
Array([0., 0., 1., 0.], dtype=float32)
```

JAX should probably assert that the input is an integer type.

Would have prevented a subtle bug in our case 🙂

### System info (python version, jaxlib version, accelerator, etc.)

N/A

**Comment by jakevdp** [comment]
Thanks for the report! Yeah it looks like we assume the input is integer, but never check that. I think my preferred fix here would be to error if the input array is not integer-typed. An alternative would be to cast float inputs to integer type. What do you think?

**Comment by danijar** [comment]
Agreed, raising an error seems better.

The case where a float is passed intentionally seems less common (and warrants explicit casting) than the case where it's an accident on the user side and should complain loudly.

**Comment by adam-hartshorne** [comment]
There are use cases when you might want one hot structure in an array using floats.  Would it be best to default to ints unless a dtype is provided specifically stating that yes you want a float etc.

**Comment by danijar** [comment]
If you have floats, you can always cast them to int before one-hot encoding them.
