### ISSUE TITLE
cond of pmap results in internal assertion error

### ISSUE THREAD

**Issue by gnecula** [jax-ml/jax#5178]
The following code should either work or throw a friendlier error message:
```
    num_devices = jax.device_count()
    x = jnp.arange(num_devices * 3, dtype=jnp.float32).reshape(num_devices, -1)
    lax.cond(True, pmap(jnp.sin), lambda x: x, x)
```

**Comment by gnecula** [comment]
@apaszke Do you expect `cond(pmap)` to work? I think it should, just like `jit(pmap)` works.

**Comment by gnecula** [comment]
BTW, the assertion that fails is
```
assert not ragged
```
in xla.axis_groups.

**Comment by froystig** [comment]
XLA does place restrictions on parallelism in cond branches. For example, if I recall correctly, a collective HLO is not allowed in a cond branch. I'm not sure that XLA's constraints rule out supporting `pmap` in a branch altogether, but I wonder if we rely on this check to guard us from producing invalid HLO today.

**Comment by gnecula** [comment]
In principle, a pmap inside a cond should work, lifting the pmap to the top level as we do for jit. But it makes sense to not allow a collective in a cond branch, so perhaps the easiest and clearest strategy is to disallow it and to give a nice error message.

**Comment by apaszke** [comment]
This seems like a tough call, and IMO we should also forbid pmap/xmap inside conditionals too, because otherwise we might violate the user expectation on how many devices the function actually uses.

**Comment by selamw1** [comment]
Hi @gnecula 
I executed the aforementioned code using two GPUs, and it produced the expected output, accompanied by a user warning indicating that the jitted function cond includes a pmap. Could you please verify this behavior with JAX 0.4.23 and confirm closure of this issue once resolved?

```Python
import jax
print(jax.__version__) # -> 0.4.23

import jax.numpy as jnp
import jax.lax as lax
num_devices = jax.device_count()
print('num_devices: ', num_devices) # -> num_devices:  2

x = jnp.arange(num_devices * 3, dtype=jnp.float32).reshape(num_devices, -1)
lax.cond(True, jax.pmap(jnp.sin), lambda x: x, x)
```
Output:
```
/home/selamw/.local/lib/python3.8/site-packages/jax/_src/dispatch.py:290: UserWarning: The jitted function cond includes a pmap. 
Using jit-of-pmap can lead to inefficient data movement, as the outer jit does not preserve sharded data representations and instead collects input and output arrays onto a single device. Consider removing the outer jit unless you know what you're doing. See https://github.com/google/jax/issues/2926.
  warnings.warn(
Array([[ 0.        ,  0.841471  ,  0.90929747],
       [ 0.14112   , -0.7568025 , -0.9589243 ]], dtype=float32)
```
